#!/bin/sh

echo "* Mounting /proc..."
mount -t proc /proc /proc

echo "* Mounting /sys..."
mount -t sysfs none /sys

echo "* Mounting /dev/pts..."
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo "* Mounting /dev/shm..."
mkdir /dev/shm
mount -t tmpfs none /dev/shm

echo "* Starting system loggers..."
syslogd

echo "* Creating devices..."
/sbin/mdev -s

echo "* Configuring loopback interface..."
ifconfig lo 127.0.0.1

echo "* Configuring network from kernel command-line..."
ifconfig eth0 up
udhcpc

echo "* Setting hostname..."
hostname lgtv

echo "* Starting telnetd..."
telnetd -l /bin/sh

echo "* Starting inetd..."
inetd

